[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Empirikos = "cab608d6-c565-4ea1-96d6-ce5441ba21b0"
EmpirikosBNP = "ea739e02-4d30-4a0b-9098-9554a276d33c"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
MultipleTesting = "f8716d33-7c4a-5097-896f-ce0ecbd3ef6b"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
RCall = "6f49c342-dc21-5d91-9882-a32aef131414"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
